language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

jdk: oraclejdk7

notifications:
  email: false

sudo: false

before_install:
  - chmod +x ./gradlew

script:
  - ./gradlew clean build