language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - android-sdk-license-5be876d5

jdk: oraclejdk7

notifications:
  email: false

sudo: false

before_install:
  - chmod +x ./gradlew

script:
  - ./gradlew clean build